server:
  port: 8080
spring:
  application:
    name: "JavaNoSql"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://localhost:27017/test"
      #uri: "mongodb://usertest:qytgZK9qt8ZV3I@docdb-2024-07-02-15-28-30.cluster-cptsrelsr8pt.us-east-1.docdb.amazonaws.com:27017/test?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

logging:
  level:
    root: INFO